name: Eslint
on: [push]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Eslint Check (renegade.fi)
        working-directory: ./renegade.fi
        run: |
          npm ci
          npx eslint src/ --ext .tsx --config ./.eslintrc.js
      - name: Eslint Check (docs.renegade.fi)
        working-directory: ./docs.renegade.fi
        run: |
          npm ci
          npx eslint src/ --ext .js --config ./.eslintrc.js
      - uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install
          dir: "testnet.renegade.fi"
      - name: Eslint Check (testnet.renegade.fi)
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: lint
          dir: "testnet.renegade.fi"
